version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/app
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        # networks:
        #     - code-network
    php:
        image: php:7.3.6-fpm
        volumes:
            - ./src:/app
        # networks:
        #     - code-network

    composer:
        image: composer:1.8.6
        command: install && dump-autoload -o
        volumes:
            - ./src:/app

    db:
        image: mariadb
        ports:
            - '3306:3306'
        command: --init-file /init.sql
        volumes:
            - ./sql/setup.sql:/init.sql
        environment:
            - MYSQL_ROOT_PASSWORD=1234

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=db
        restart: always
        ports:
            - 8081:80
        volumes:
            - /sessions
        links:
            - db 

        

# networks:
#     code-network:
#         driver: bridge
